(()=>{'use strict';
const $=s=>document.querySelector(s), canvas=$('#screen'),ctx=canvas.getContext('2d');
const C={ink:'#202f35',muted:'#818980',paper:'#fcfbf6',line:'#dce1d7',q:'#3768d8',k:'#9659bd',v:'#168873',a:'#ce882a',red:'#ce6257'};
const X=[[1,0,0,0],[0,1,0,0],[1,0,2,1]];
const WQ=[[1,0,1,0],[0,1,0,1],[0,.5,0,.5],[0,0,0,0]],WK=[[1,1,1,1],[1,1,0,0],[0,-1,0,-1],[0,0,0,0]],WV=[[2,0],[0,2],[-.5,.5],[0,0]];
const WO=[[1,0,1,0],[0,1,0,1]],W1=[[1,0,0,0,1,-1,1,-1],[0,1,0,0,0,0,0,0],[0,0,1,0,1,-1,1,-1],[0,0,0,1,0,0,0,0]],W2=[[1,0,0,0],[0,0,0,0],[0,0,1,0],[0,0,0,0],[1,1,1,0],[0,0,0,0],[0,0,0,1],[0,0,0,0]];
const transpose=a=>a[0].map((_,j)=>a.map(r=>r[j])),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),mul=(a,b)=>a.map(r=>transpose(b).map(c=>dot(r,c))),softmax=a=>{let m=Math.max(...a),e=a.map(x=>Math.exp(x-m)),s=e.reduce((a,b)=>a+b,0);return e.map(x=>x/s)},add=(a,b)=>a.map((x,i)=>x+b[i]),stats=a=>{let mean=a.reduce((s,x)=>s+x,0)/a.length,v=a.reduce((s,x)=>s+(x-mean)**2,0)/a.length;return {mean,variance:v,sd:Math.sqrt(v+1e-5)}},norm=a=>{let s=stats(a);return a.map(x=>(x-s.mean)/s.sd)},f=(n,d=4)=>Number(n.toFixed(d)).toString();
const Q=mul(X,WQ),K=mul(X,WK),V=mul(X,WV),S=mul(Q,transpose(K)),A=S.map(r=>softmax(r.map(x=>x/2))),Z=mul(A,V),a=mul([Z[2]],WO)[0],res=add(X[2],a),ln=norm(res),hidden=mul([ln],W1)[0],relu=hidden.map(x=>Math.max(0,x)),ff=mul([relu],W2)[0],res2=add(ln,ff),Y=norm(res2);
const pe=p=>[Math.sin(p),Math.cos(p),Math.sin(p/100),Math.cos(p/100)],E=X.map((r,i)=>r.map((v,j)=>v-pe(i)[j]));
const chapters=[];function chapter(id,title,desc,cues){chapters.push({id,title,desc,cues:cues.map(text=>({text,duration:Math.max(7,text.split(/\s+/).length/2.05+1.8)}))})}
chapter('context','El contexto lo cambia todo','Primero una intuición. Después, cada cuenta.',[
'Escucha esta frase: el tamal estaba masacotudo. Aunque no conozcas la última palabra, las otras dos ya te dan una pista.',
'Masacotudo describe cómo estaba el tamal. Para descubrir esa relación, su representación necesita recibir información de las otras posiciones.',
'Observa los hilos. Atención significa calcular cuánto de cada posición incorporamos a una representación. No es leer mentes: es comparar números y mezclarlos.',
'Vamos a seguir una sola palabra durante todo el viaje. Verás de dónde sale cada número. Puedes pausar o retroceder cuando quieras.'
]);
chapter('embedding','Una palabra se vuelve números','Contenido + posición = entrada al bloque.',[
'Para hacer cuentas necesitamos números. Simplificaremos: cada palabra será un token, aunque un token real también puede ser una parte de palabra.',
'Un embedding asigna un vector a cada token. Aquí tendrá cuatro coordenadas. Las casillas no tienen significados humanos fijos: son números que un modelo puede aprender.',
'También importa el orden. Sumamos una señal de posición. La palabra aporta contenido y la posición aporta dónde está. Sumar conserva las cuatro coordenadas.',
'Para la tercera posición usamos p igual a dos, porque empezamos a contar desde cero. Esta es la señal sinusoidal con cuatro coordenadas.',
'En este ejemplo escogimos los embeddings para que, después de sumar posición, las entradas sean sencillas. Masacotudo entra al bloque como uno, cero, dos, uno.',
'Esta matriz se llama X. Cada fila es una posición y cada columna es una coordenada. Tres posiciones por cuatro coordenadas. Conservaremos estos datos durante toda la cuenta.'
]);
chapter('qkv','Tres versiones de la misma palabra','Q busca · K permite comparar · V aporta contenido.',[
'De cada entrada salen tres versiones. Query expresa qué buscamos; Key sirve para comparar; Value es la información que vamos a transportar.',
'Las tres versiones salen de multiplicar X por tres matrices distintas: W de Q, W de K y W de V. Aquí elegimos pesos pequeños para poder revisar las cuentas.',
'Por ejemplo, la segunda coordenada de la Query de masacotudo es uno por cero, más cero por uno, más dos por un medio, más uno por cero. El resultado es uno.',
'La Query completa resulta uno, uno, uno, uno. Su Key es uno, menos uno, uno, menos uno. Su Value tiene solo dos coordenadas: uno, uno.',
'No confundas sus trabajos. Q y K deciden la compatibilidad. El contenido que finalmente se mezcla sale de V. Las matrices de pesos completas están en Ver datos.'
]);
chapter('scores','La búsqueda se convierte en una cuenta','Multiplicar coordenadas. Sumar resultados.',[
'La Query de masacotudo pregunta primero por tamal. Colocamos su Query frente a la Key de tamal: ambos son uno, uno, uno, uno.',
'Emparejamos coordenadas. La primera cuenta es uno por uno. La segunda también. Lo mismo ocurre con las otras dos.',
'Sumamos los cuatro productos: uno más uno más uno más uno es cuatro. Ese cuatro es compatibilidad, todavía no es un porcentaje.',
'Ahora comparamos con estaba. Su Key es uno, uno, cero, cero. Los productos suman dos. El procedimiento es exactamente el mismo.',
'Finalmente compara consigo mismo. Uno menos uno más uno menos uno da cero. Así obtenemos la fila cuatro, dos, cero.',
'Repetimos para las demás Queries y obtenemos Q por K transpuesta. Fila significa quién pregunta. Columna significa a quién consulta. Seguiremos la última fila.'
]);
chapter('softmax','De compatibilidad a proporciones','4, 2, 0 → 2, 1, 0 → 66.52 %, 24.47 %, 9.00 %.',[
'Los productos punto pueden crecer con la dimensión. Dividimos por la raíz de d k. Tenemos cuatro coordenadas: la raíz de cuatro es dos.',
'Cuatro dividido por dos es dos. Dos dividido por dos es uno. Cero dividido por dos sigue siendo cero. El orden no cambia; cambia la escala.',
'Ahora softmax. Elevamos e a cada número: e al cuadrado, e a la uno, e a la cero. Obtenemos aproximadamente siete coma treinta y nueve, dos coma setenta y dos, y uno.',
'Sumamos las tres cantidades. El total es once coma diez setenta y cuatro. Cada cantidad se divide por ese mismo total.',
'Así aparecen los pesos: sesenta y seis coma cincuenta y dos por ciento, veinticuatro coma cuarenta y siete, y nueve. Son positivos y juntos suman cien por ciento.',
'Mira cómo se reparte la misma cantidad total. Tamal recibe la porción mayor, pero no eliminamos las demás. Hicimos softmax sobre una fila, no sobre toda la matriz.'
]);
chapter('values','Ahora sí viaja la información','Los pesos multiplican Values, no Keys.',[
'Ya decidimos cuánto mirar. Ahora los Values viajan por esas conexiones. Tamal aporta dos, cero. Estaba aporta cero, dos. Masacotudo aporta uno, uno.',
'Multiplicamos cada Value por su peso. El primero queda uno coma treinta y tres, cero. El segundo, cero, cero coma cuarenta y nueve. El tercero aporta cero coma cero nueve en ambas coordenadas.',
'Para la primera coordenada sumamos uno coma treinta y tres, más cero, más cero coma cero nueve. El resultado es aproximadamente uno coma cuarenta y dos cero cinco.',
'Para la segunda sumamos cero, más cero coma cuarenta y nueve, más cero coma cero nueve. El resultado es cero coma cincuenta y siete noventa y cinco.',
'Este es z tres: la salida de atención para masacotudo. Es un vector contextual construido con información de tres posiciones. Todavía no es una palabra predicha.'
]);
chapter('mask','Una ventana que no deja ver el futuro','La máscara se suma antes del softmax.',[
'Hagamos una pausa dentro de la historia. Cuando generamos texto, una posición no puede usar palabras que todavía no han llegado. Para eso existe la máscara causal.',
'Mira la primera fila: solo puede mirar su propia posición. Las otras dos quedan tapadas. La segunda puede mirar las dos primeras. La tercera puede mirar las tres.',
'En los scores futuros sumamos menos infinito, antes del softmax. La exponencial de menos infinito es cero. Así esas conexiones reciben exactamente peso cero.',
'Los pesos permitidos se vuelven a normalizar. La primera fila queda uno, cero, cero. La segunda, cero coma seis dos dos cinco y cero coma tres siete siete cinco, y cero.',
'La fila de masacotudo no cambia: ya era la última posición y no tenía un futuro visible. Por eso su resultado numérico anterior sigue siendo válido con esta máscara.'
]);
chapter('heads','Varias miradas en paralelo','La misma secuencia, proyecciones distintas.',[
'Un Transformer suele tener varias cabezas. Todas reciben la misma secuencia, pero cada cabeza tiene sus propias matrices de Q, K y V.',
'Los patrones pueden ser diferentes. No asignamos de antemano un significado a cada cabeza: las relaciones se aprenden. Este dibujo muestra dos miradas posibles.',
'Concatenamos las salidas y las mezclamos con W de salida. Para poder calcular todo a mano, nuestro ejemplo numérico usa una sola cabeza. Volvamos a su vector de dos números.'
]);
chapter('residual','La información nueva se suma a la anterior','Wᴼ ajusta el ancho; el atajo conserva la entrada.',[
'La atención produjo dos coordenadas, pero nuestra entrada tenía cuatro. Antes de sumarlas, multiplicamos por W de salida, una matriz de dos por cuatro.',
'En nuestro ejemplo, esa matriz copia las dos coordenadas. Obtenemos uno coma cuarenta y dos, cero coma cincuenta y ocho, uno coma cuarenta y dos, cero coma cincuenta y ocho.',
'Por el atajo residual llega la entrada original: uno, cero, dos, uno. La información anterior no desaparece. Sumamos la corrección a cada coordenada.',
'El resultado es aproximadamente dos coma cuatro dos cero cinco; cero coma cinco siete nueve cinco; tres coma cuatro dos cero cinco; y uno coma cinco siete nueve cinco.'
]);
chapter('norm','Centrar y ajustar la escala','LayerNorm trabaja dentro de una sola posición.',[
'Ahora LayerNorm. Solo miramos los cuatro números de esta posición. Primero calculamos la media: sumamos las cuatro coordenadas y dividimos por cuatro. Da dos.',
'Restamos dos a cada coordenada. Mira cómo los números se desplazan hasta quedar alrededor de cero. Esto se llama centrar.',
'Para medir la dispersión, elevamos esas diferencias al cuadrado, las sumamos y dividimos por cuatro. La varianza es aproximadamente uno coma cero nueve siete tres.',
'Tomamos la raíz de la varianza más un epsilon pequeño. Dividimos cada diferencia por ese valor. En este ejemplo gamma es uno y beta es cero.',
'La salida queda aproximadamente cero coma cuatro cero uno cuatro; menos uno coma tres cinco seis; uno coma tres cinco seis; menos cero coma cuatro cero uno cuatro. No mezclamos palabras durante LayerNorm.'
]);
chapter('ffn','Procesar lo que acaba de llegar','4 → 8 → 4: expandir, aplicar ReLU y proyectar.',[
'La atención fue la conversación entre posiciones. Ahora cada posición procesa su propio vector con la misma red feed forward. Aquí no viaja información entre palabras.',
'Multiplicamos por W uno y pasamos de cuatro a ocho coordenadas. Observa las nuevas combinaciones. Los pesos completos del ejemplo están disponibles en Ver datos.',
'Aplicamos ReLU: si el número es negativo, se vuelve cero. Si es positivo, se conserva. Mira cómo se apagan las cuatro coordenadas negativas.',
'Multiplicamos por W dos y volvemos a cuatro coordenadas. Esta segunda matriz combina las activaciones que sobrevivieron. Los sesgos de nuestro ejemplo son cero.',
'El resultado es aproximadamente dos coma uno cinco ocho nueve; uno coma siete cinco siete cinco; tres coma uno uno tres cinco; y uno coma siete cinco siete cinco. Es otra corrección para el vector.'
]);
chapter('output','La salida de un bloque completo','Un vector de cuatro coordenadas, ahora contextual.',[
'Repetimos el patrón: sumamos la salida de la feed forward a su entrada por un segundo atajo residual. Después aplicamos otra LayerNorm.',
'Llegamos al vector final de este bloque. Cada valor mostrado se calcula con las matrices del ejemplo, sin redondear los resultados intermedios.',
'Recuerda el viaje: representar, comparar, repartir, mezclar, sumar, normalizar y transformar. La dimensión final sigue siendo cuatro. Lo que cambió fue la información que contiene.'
]);
chapter('generation','¿Y cuándo aparece una palabra?','Bloques → logits → probabilidades → siguiente token.',[
'Un vector contextual aún no es texto. En un modelo de lenguaje causal apilamos bloques y proyectamos el último vector a un score por token del vocabulario. Esos scores se llaman logits.',
'Otro softmax produce probabilidades sobre el vocabulario. Es un softmax distinto: antes repartíamos atención entre posiciones; ahora repartimos probabilidad entre posibles tokens.',
'Aquí mostramos probabilidades ilustrativas, no calculadas con el bloque anterior. Elegimos un token, lo añadimos a la secuencia y repetimos el proceso para producir el siguiente.',
'Así se construye texto, un token a la vez. Ya recorriste el interior de un bloque y viste cómo se conecta con la generación. Puedes repetir cualquier parte desde los capítulos.'
]);
let total=0;const cues=[];chapters.forEach((ch,ci)=>{ch.start=total;ch.cues.forEach((cue,bi)=>{cue.start=total;cue.ci=ci;cue.bi=bi;total+=cue.duration;cue.end=total;cues.push(cue)});ch.end=total});
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=x=>{x=clamp(x);return x*x*(3-2*x)},mix=(a,b,t)=>a+(b-a)*t;
let time=0,playing=false,started=false,voice=true,captions=true,rate=1,last=0,active=-1,utterance=null,speechDone=true,speechVersion=0,speechDeadline=0,speechPaused=false,pauseAt=0;
function text(s,x,y,size=24,color=C.ink,align='center',weight=450,font='sans'){ctx.fillStyle=color;ctx.font=`${weight} ${size}px ${font==='serif'?'Georgia,serif':'system-ui,-apple-system,sans-serif'}`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(s,x,y)}
function box(x,y,w,h,fill='#fff',stroke=C.line,r=16){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke()}}
function line(x1,y1,x2,y2,color=C.line,width=2,progress=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(mix(x1,x2,progress),mix(y1,y2,progress));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()}
function path(x1,y1,x2,y2,color=C.a,width=3,p=1,bend=-80){ctx.beginPath();ctx.moveTo(x1,y1);ctx.bezierCurveTo(x1,y1+bend,x2,y2+bend,x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash([1600]);ctx.lineDashOffset=1600*(1-p);ctx.stroke();ctx.setLineDash([])}
function circle(x,y,r,fill,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function alpha(op,fn){ctx.save();ctx.globalAlpha*=clamp(op);fn();ctx.restore()}
function title(kicker,heading,sub){text(kicker.toUpperCase(),70,58,13,C.muted,'left',600);text(heading,70,114,43,C.ink,'left',400,'serif');if(sub)text(sub,70,166,18,C.muted,'left')}
function pill(s,x,y,color=C.q,w=190){box(x-w/2,y-28,w,56,color+'10',color,13);text(s,x,y,22,color,'center',550)}
function vector(values,x,y,color=C.q,cell=80,label,highlight=-1){if(label)text(label,x+(values.length*cell)/2,y-31,18,color);values.forEach((v,i)=>{box(x+i*cell+3,y,cell-6,61,i===highlight?color+'25':'#ffffff',i===highlight?color:C.line,10);text(typeof v==='number'?f(v):v,x+i*cell+cell/2,y+31,Math.min(values.length>4?17:23,(cell-16)/(String(typeof v==='number'?f(v):v).length*.62)),color,'center',550)})}
function matrix(values,x,y,color=C.q,cell=72,row=-1){values.forEach((r,i)=>{r.forEach((v,j)=>{box(x+j*cell,y+i*58,cell-5,52,i===row?color+'17':'#ffffff',i===row?color:C.line,8);text(typeof v==='number'?f(v,3):v,x+j*cell+(cell-5)/2,y+i*58+26,20,i===row?color:C.ink)})})}
function note(s,y=625,color=C.muted){text(s,720,y,19,color)}
function arrow(x1,y1,x2,y2,color=C.line,p=1){line(x1,y1,x2,y2,color,2,p);if(p>.95){let a=Math.atan2(y2-y1,x2-x1);line(x2,y2,x2-10*Math.cos(a-.5),y2-10*Math.sin(a-.5),color,2);line(x2,y2,x2-10*Math.cos(a+.5),y2-10*Math.sin(a+.5),color,2)}}
function particle(x1,y1,x2,y2,p,color,r=6){circle(mix(x1,x2,p),mix(y1,y2,p),r,color)}
function tokens(y=310,selected=2,positions=[310,720,1130]){['tamal','estaba','masacotudo'].forEach((s,i)=>{pill(s,positions[i],y,i===selected?C.q:C.muted,i===2?240:180);text(`posición ${i}`,positions[i],y+53,14,C.muted)})}
function grid(){ctx.fillStyle=C.paper;ctx.fillRect(0,0,1440,810);ctx.fillStyle='#d8ddd34d';for(let x=30;x<1440;x+=30)for(let y=30;y<810;y+=30){ctx.beginPath();ctx.arc(x,y,.85,0,Math.PI*2);ctx.fill()}}
const renders={};
renders.context=(u,t)=>{title('01 · Antes de las fórmulas','Las palabras no viven solas.','Una misma palabra se interpreta con ayuda de su contexto.');tokens(375);let p=ease(u-1);path(1100,340,310,340,C.a,5,p,-130);path(1100,340,720,340,C.a,3,p,-100);alpha(p,()=>{text('¿cómo estaba qué?',900,236,24,C.a,'center',400,'serif');text('el contexto llega a su representación',720,550,23,C.muted)});if(u>2){for(let i=0;i<7;i++){let p=((t*.11+i/7)%1);particle(310,435,1130,435,p,C.a,4)}arrow(310,435,1130,435,C.a)}alpha(ease(u-3),()=>note('No es magia: comparar vectores y mezclar información.',620,C.q))};
renders.embedding=(u)=>{title('02 · Embedding + posición','De una palabra a cuatro coordenadas.','Cada fila pertenece a una posición.');if(u<2){tokens(mix(340,270,ease(u-1)));alpha(ease(u-.7),()=>{[E[0],E[1],E[2]].forEach((v,i)=>vector(v,150+i*405,390,C.q,75));text('embedding aprendido · E',720,520,21,C.q)})}else if(u<5){let p=pe(2);pill('masacotudo',720,221,C.q,240);text('contenido',450,257,18,C.q);vector(E[2],290,295,C.q,100,'');text('+',720,326,40,C.muted);text('posición p = 2',990,257,18,C.a);vector(p,785,295,C.a,100);alpha(ease(u-2),()=>{text('PE(p) = [sin(p), cos(p), sin(p/100), cos(p/100)]',720,424,25,C.a)});alpha(ease(u-3),()=>{text('=',245,526,38,C.muted);vector(X[2],290,495,C.q,100,'X₃ = E₃ + PE(2)');text('4 números antes. 4 números después.',1000,526,19,C.muted)});alpha(ease(u-4),()=>note('X₃ = [1, 0, 2, 1] será nuestra entrada durante todo el ejemplo.',640,C.q))}else{['tamal','estaba','masacotudo'].forEach((s,i)=>text(s,440,310+i*70,25,i===2?C.q:C.muted,'right'));matrix(X,510,280,C.q,100,2);text('X  ∈  ℝ³ˣ⁴',1100,375,39,C.q,'center',400,'serif');note('Números elegidos para aprender; no son embeddings de un modelo entrenado.')}};
renders.qkv=(u)=>{title('03 · Proyecciones','Una palabra. Tres trabajos distintos.','Todas las posiciones usan las mismas matrices de proyección.');vector(X[2],530,215,C.ink,95,'entrada X₃');const colors=[C.q,C.k,C.v],labels=['Q · busca','K · compara','V · aporta'],out=[Q[2],K[2],V[2]];[270,720,1170].forEach((x,i)=>{arrow(720,280,x,365,colors[i],ease(u));pill(['× WQ','× WK','× WV'][i],x,395,colors[i],140);alpha(ease(u-.5),()=>{text(labels[i],x,468,23,colors[i]);vector(out[i],x-out[i].length*37,506,colors[i],74)})});if(u>=2&&u<4){box(300,620,840,64,'#eff3fc',C.q);text('q₃₂ = 1×0 + 0×1 + 2×½ + 1×0 = 1',720,652,28,C.q)}else alpha(ease(u-3),()=>note('Q y K buscan coincidencias. V es la información que viaja.',642,C.v))};
renders.scores=(u)=>{title('04 · Producto punto','Comparemos una Query con cada Key.','Multiplicamos coordenada a coordenada y sumamos.');if(u<5){let j=u<3?0:u<4?1:2;let pp=u<3?u:u-j-2;vector(Q[2],410,250,C.q,110,'q₃ · masacotudo');vector(K[j],410,400,C.k,110,`k${j+1} · ${['tamal','estaba','masacotudo'][j]}`);for(let k=0;k<4;k++){let p=ease(u<3?u-1-k*.13:pp);alpha(p,()=>{line(465+k*110,318,465+k*110,380,C.a,2);text('×',465+k*110,350,24,C.a);text(String(Q[2][k]*K[j][k]),465+k*110,525,31,C.a);if(k<3)text('+',520+k*110,525,24,C.muted)})}let p=ease(u<3?u-2:pp-.2);alpha(p,()=>{text('=',890,525,30,C.muted);pill(String(S[2][j]),1010,525,C.a,115);note(`q₃ · k${j+1} = ${S[2][j]}  ·  compatibilidad, todavía no probabilidad`,640,C.a)})}else{matrix(Q,140,300,C.q,76,2);text('×',490,388,35,C.muted);matrix(transpose(K),550,273,C.k,72);text('=',845,388,35,C.muted);matrix(S,920,300,C.a,96,2);text('Q · filas que preguntan',292,540,20,C.q);text('Kᵀ · columnas consultadas',655,570,20,C.k);text('S = QKᵀ',1065,540,24,C.a);note('Seguimos la fila 3: [4, 2, 0]',655,C.a)}};
renders.softmax=(u)=>{title('05 · Escala + softmax','De puntajes a una cantidad que se reparte.','Una fila de atención siempre suma 1.');let raw=[4,2,0],scaled=[2,1,0];if(u<2){raw.forEach((v,i)=>{let x=360+i*350;line(x,480,x,480-mix(v,v/2,ease(u-1))*60,C.q,40);text(f(mix(v,v/2,ease(u-1)),1),x,510,35,C.q);text(['tamal','estaba','masacotudo'][i],x,565,19,C.muted)});pill('÷ √4 = ÷ 2',720,244,C.a,270)}else if(u<4){scaled.forEach((v,i)=>{let x=350+i*365;text(`e${['²','¹','⁰'][i]}`,x,280,43,C.q);arrow(x,324,x,373,C.line);text(f(Math.exp(v)),x,422,32,C.a)});alpha(ease(u-2.4),()=>{line(235,479,1210,479,C.line,2);text('7.3891 + 2.7183 + 1 = 11.1074',720,536,31,C.ink)});alpha(ease(u-3),()=>note('Cada exponencial se divide por el mismo total.',631,C.a))}else{let p=ease(u-4);A[2].forEach((v,i)=>{let y=290+i*95;text(['tamal','estaba','masacotudo'][i],295,y+25,22,C.muted,'right');box(340,y,710,50,'#efefe8',null,8);box(340,y,Math.max(2,710*v*p),50,C.a,null,8);text(`${(v*100).toFixed(2)} %`,1150,y+25,29,C.a);text(`${f(Math.exp(scaled[i]))} / 11.1074`,690,y+25,19,C.ink)});alpha(ease(u-4.5),()=>{pill('Σ = 1.0000',720,612,C.a,230)});if(u>5){for(let i=0;i<100;i++){let col=i<67?C.q:i<91?C.k:C.v;circle(238+i*9.7,688,3.5,col)}}}};
renders.values=(u,t)=>{title('06 · Promedio ponderado','Los Values viajan. Los pesos regulan cuánto.','z₃ = a₃₁v₁ + a₃₂v₂ + a₃₃v₃');let p=ease(u-1);for(let i=0;i<3;i++){let x=300+i*420;text(['tamal','estaba','masacotudo'][i],x,234,21,C.muted);vector(V[i],x-90,270,C.v,90);text(`× ${f(A[2][i])}`,x,376,27,C.a);arrow(x,411,x,451,C.v);vector(V[i].map(v=>v*A[2][i]*p),x-115,465,C.v,115);if(u>1&&u<2){for(let k=0;k<4;k++)particle(x,405,x,452,(t*.3+k/4)%1,C.v,3+A[2][i]*5)}}if(u>=2){alpha(ease(u-2),()=>{box(320,567,800,96,'#eaf4ef',C.v);let j=u<3?0:1;let equation=V.map((r,i)=>f(r[j]*A[2][i])).join(' + ');text(`${equation} = ${f(Z[2][j])}`,720,610,31,C.v)})}if(u>=4){box(280,558,880,115,'#eaf4ef',C.v);text('SALIDA DE ATENCIÓN',720,582,13,C.v);text(`z₃ = [${Z[2].map(v=>f(v)).join(',  ')}]`,720,632,38,C.v,'center',500)}};
renders.mask=(u,t)=>{title('07 · Máscara causal','El futuro todavía no está disponible.','Primero tapamos scores. Después calculamos softmax.');let labels=['tamal','estaba','masacotudo'];labels.forEach((s,j)=>text(s,635+j*190,246,19,C.muted));labels.forEach((s,i)=>text(s,460,310+i*91,21,C.muted,'right'));for(let i=0;i<3;i++)for(let j=0;j<3;j++){let future=j>i,p=ease(u-1);box(555+j*190,272+i*91,160,76,future?`rgba(206,98,87,${.07+p*.12})`:'#edf5ef',future?C.red:C.v,12);let val=u>=3?f(softmax(S[i].map((x,k)=>k>i?-Infinity:x/2))[j]):u>=2?(future?'−∞':f(S[i][j]/2)):f(S[i][j]/2);text(val,635+j*190,310+i*91,29,future?C.red:C.v);if(future&&u>=1&&u<2){alpha(p,()=>{line(570+j*190,285+i*91,700+j*190,335+i*91,C.red,3);line(700+j*190,285+i*91,570+j*190,335+i*91,C.red,3)})}}if(u<3){text(u>=2?'e⁻∞ = 0':'Solo puedes usar pasado y presente.',720,604,33,u>=2?C.red:C.muted)}else{text('Cada fila permitida vuelve a sumar 1.',720,588,24,C.v);alpha(ease(u-4),()=>note('La última fila no cambia: no tenía posiciones futuras.',647,C.q))}};
renders.heads=(u,t)=>{title('08 · Multi-head','La misma frase, distintas proyecciones.','Diagrama conceptual · nuestro cálculo numérico usa una cabeza.');pill('X · todas las posiciones',720,231,C.ink,310);[420,1020].forEach((x,i)=>{let color=i?C.k:C.q;arrow(720,264,x,335,color,ease(u));box(x-200,350,400,164,color+'0c',color,18);text(`cabeza ${i+1}`,x,379,21,color);[x-110,x,x+110].forEach((xx,j)=>{circle(xx,448,20,color+'20',color);text(['t','e','m'][j],xx,448,16,color)});path(x+110,425,i?x:x-110,425,color,4,ease(u-1),-25);arrow(x,530,720,590,color,ease(u-1.6))});alpha(ease(u-2),()=>{pill('concatenar → Wᴼ',720,620,C.v,330)})};
renders.residual=(u,t)=>{title('09 · Proyección + residual','Lo nuevo se encuentra con lo que ya estaba.','Sumamos vectores del mismo tamaño.');vector(Z[2],245,240,C.v,115,'z₃ · 2 coordenadas');text('×',526,270,32,C.muted);matrix(WO,585,215,C.v,75);text('Wᴼ · 2 × 4',730,369,18,C.v);alpha(ease(u-1),()=>{arrow(930,273,1030,273,C.v);vector(a,500,430,C.v,110,'a · 4 coordenadas')});alpha(ease(u-2),()=>{path(255,345,465,570,C.q,3,1,80);text('atajo: X₃ = [1, 0, 2, 1]',270,506,22,C.q);text('+',455,460,32,C.q);vector(res,500,575,C.ink,110,'X₃ + a')});alpha(ease(u-3),()=>{pill('original + corrección',1170,575,C.a,300)})};
renders.norm=(u)=>{title('10 · LayerNorm','Primero centrar. Después ajustar la escala.','Solo normalizamos las coordenadas de esta posición.');let m=stats(res),center=ease(u-1),scale=ease(u-3),vals=res.map(v=>mix(v-m.mean*center,(v-m.mean)/m.sd,scale));line(260,430,1220,430,C.line,2);[-2,-1,0,1,2,3,4].forEach(v=>{let xx=520+v*140;line(xx,423,xx,437,C.muted);text(String(v),xx,459,16,C.muted)});vals.forEach((v,i)=>{let xx=520+v*140;circle(xx,340+(i%2)*45,19,[C.q,C.k,C.v,C.a][i]);text(f(v),xx,290+(i%2)*45,22,[C.q,C.k,C.v,C.a][i]);line(xx,370+(i%2)*45,xx,424,C.line,1)});if(u<1)note('μ = (2.4205 + 0.5795 + 3.4205 + 1.5795) / 4 = 2',555,C.q);else if(u<2)note('Restar la media: r − μ',555,C.q);else if(u<3){note(`σ² = Σ(rᵢ − μ)² / 4 = ${f(m.variance)}`,555,C.a);text('Cuadrados → suma → dividir por 4',720,615,20,C.muted)}else{note(`(r − μ) / √(σ² + ε)     ·     ε = 0.00001`,555,C.q);alpha(ease(u-4),()=>vector(ln,460,615,C.q,130,'salida normalizada'))}};
renders.ffn=(u,t)=>{title('11 · Feed forward','Después de conversar, cada posición procesa.','Las mismas matrices se aplican por separado a cada posición.');let cols=[300,720,1140],ys=n=>Array.from({length:n},(_,i)=>n===8?250+i*48:295+i*92);for(let k=0;k<2;k++){let from=ys(k?8:4),to=ys(k?4:8);for(let i=0;i<from.length;i++)for(let j=0;j<to.length;j++){let mat=k?W2:W1;if(mat[i][j]!==0)line(cols[k]+40,from[i],cols[k+1]-42,to[j],(k?C.v:C.q)+'30',1.5,ease(u-(k?3:.4)))}}ln.forEach((v,i)=>{pill(f(v),cols[0],ys(4)[i],C.q,120)});alpha(ease(u-.6),()=>hidden.forEach((v,i)=>{let p=ease(u-2);let out=mix(v,Math.max(0,v),p),off=v<0&&u>2;box(cols[1]-61,ys(8)[i]-20,122,40,off?'#efeee7':C.k+'12',off?C.line:C.k,10);text(f(out),cols[1],ys(8)[i],20,off?C.muted:C.k)}));alpha(ease(u-3),()=>ff.forEach((v,i)=>pill(f(v),cols[2],ys(4)[i],C.v,150)));text('4 coordenadas',300,680,18,C.q);text(u<2?'W₁ · 8 coordenadas':'ReLU · max(0, x)',720,680,18,C.k);text('W₂ · 4 coordenadas',1140,680,18,C.v);if(u>=2&&u<3)text('Los negativos se vuelven 0.',1120,230,22,C.red)};
renders.output=(u)=>{title('12 · Salida del bloque','Mismo tamaño. Información nueva.','Último residual + LayerNorm.');if(u<1.7){vector(ln,300,260,C.q,115,'entrada de la FFN');text('+',820,290,38,C.muted);vector(ff,900,260,C.v,100,'corrección FFN');arrow(720,350,720,416,C.line);vector(res2,470,448,C.ink,130,'segundo residual');alpha(ease(u),()=>{text(`μ = ${f(stats(res2).mean)}     σ = ${f(stats(res2).sd)}`,720,598,26,C.muted)})}else{vector(X[2],440,255,C.muted,140,'entrada X₃');arrow(720,344,720,413,C.q);vector(Y,440,450,C.q,140,'salida Y₃');note('Comparar → repartir → mezclar → sumar → normalizar → transformar',625,C.q)}};
renders.generation=(u,t)=>{title('13 · De vectores a texto','Un bloque no predice una palabra por sí solo.','Para generar texto necesitamos una salida sobre el vocabulario.');if(u<2){['bloques','último vector','logits','softmax'].forEach((s,i)=>{let x=260+i*300;box(x-100,292,200,102,i===3?C.a+'13':'#fff',i===3?C.a:C.line,17);text(s,x,343,22,i===3?C.a:C.ink);if(i<3)arrow(x+110,343,x+188,343,C.q,ease(u-i*.2))});alpha(ease(u-.5),()=>{text('Antes: probabilidad sobre POSICIONES.',720,489,26,C.q);text('Ahora: probabilidad sobre TOKENS DEL VOCABULARIO.',720,547,26,C.a)})}else{pill('el tamal estaba',425,294,C.ink,370);arrow(645,294,795,294,C.q);['masacotudo','delicioso','frío'].forEach((s,i)=>{let y=260+i*94;box(850,y,360,61,'#fff',i===0?C.q:C.line,10);box(855,y+5,[230,87,28][i],51,C.q+'15',null,6);text(s,876,y+30,22,i===0?C.q:C.muted,'left');text(['65 %','25 %','8 %'][i],1174,y+30,19,C.muted,'right')});text('otros tokens: 2 % · probabilidades ilustrativas',1035,571,15,C.muted);alpha(ease(u-2.5),()=>{pill('el tamal estaba masacotudo …',720,646,C.q,600)})}};
function cover(t){grid();ctx.save();ctx.translate(565,45);let ps=[[300,280],[660,205],[535,485]];path(...ps[0],...ps[1],C.q,2,1,-80);path(...ps[1],...ps[2],C.k,2,1,50);path(...ps[2],...ps[0],C.v,2,1,30);for(let i=0;i<3;i++){let [x,y]=ps[i];circle(x,y,75,[C.q,C.k,C.v][i]+'0c');pill(['tamal','estaba','masacotudo'][i],x,y,[C.q,C.k,C.v][i],i===2?250:180);vector([[1,0,0,0],[0,1,0,0],[1,0,2,1]][i],x-110,y+58,[C.q,C.k,C.v][i],55)}text('EL CONTEXTO TRANSFORMA.',460,655,12,C.muted);ctx.restore()}
function cueAt(t){let i=cues.findIndex(c=>t<c.end);return i<0?cues.length-1:i}
function draw(){grid();if(!started){cover(time);return}const cue=cues[cueAt(time)],ch=chapters[cue.ci],u=cue.bi+clamp((time-cue.start)/cue.duration);ctx.save();ctx.scale(1,.88);renders[ch.id](u,time);ctx.restore();if($('#zoomDialog').open){$('#zoomCanvas').getContext('2d').drawImage(canvas,0,0);$('#zoomCaption').textContent=cue.text}ctx.fillStyle=C.q;ctx.fillRect(0,0,1440*(time/total),3);canvas.setAttribute('aria-label',`${ch.title}. ${cue.text}`)}
const clock=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function cancelSpeech(){speechPaused=false;speechVersion++;if('speechSynthesis'in window)window.speechSynthesis.cancel();speechDone=true;utterance=null}
function speak(cue){cancelSpeech();if(!voice||!playing||!('speechSynthesis'in window))return;const version=speechVersion;utterance=new SpeechSynthesisUtterance(cue.text);let voices=speechSynthesis.getVoices();utterance.voice=voices.find(v=>v.lang==='es-CO')||voices.find(v=>v.lang==='es-MX')||voices.find(v=>v.lang.startsWith('es'))||null;utterance.lang=utterance.voice?.lang||'es-ES';utterance.rate=rate;utterance.pitch=1;speechDone=false;speechDeadline=performance.now()+Math.max(30000,cue.duration*2500/rate);utterance.onend=()=>{if(version===speechVersion)speechDone=true};utterance.onerror=()=>{if(version===speechVersion){speechDone=true;$('#status').textContent='La voz no está disponible. La explicación continúa con subtítulos.'}};speechSynthesis.speak(utterance)}
function update(force=false){const i=cueAt(time),cue=cues[i],ch=chapters[cue.ci];$('#seek').value=time;$('#clock').textContent=`${clock(time)} / ${clock(total)}`;$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',playing?'Pausar':'Reproducir');$('#back').disabled=time===0;$('#forward').disabled=time>=total;$('#replay').hidden=time<total;if(i!==active||force){active=i;$('#caption').textContent=cue.text;$('#caption').hidden=!started||!captions;$('#chapterLabel').textContent=`${String(cue.ci+1).padStart(2,'0')} / ${ch.title}`;$('#sceneTitle').textContent=ch.title;$('#sceneDescription').textContent=ch.desc;document.querySelectorAll('.chapter').forEach((b,j)=>b.classList.toggle('active',j===cue.ci));if(playing)speak(cue)}}
function start(){if(!started){started=true;$('#welcome').hidden=true;$('#caption').hidden=!captions}if(time>=total)time=0;playing=true;last=performance.now();if(speechPaused&&utterance&&!speechDone){speechPaused=false;speechDeadline+=performance.now()-pauseAt;speechSynthesis.resume();update()}else{active=-1;update(true)}draw()}
function pause(){playing=false;if(voice&&utterance&&!speechDone&&'speechSynthesis'in window){speechSynthesis.pause();speechPaused=true;pauseAt=performance.now()}else cancelSpeech();update()}
function seek(t){cancelSpeech();time=clamp(t,0,total);if(!started){started=true;$('#welcome').hidden=true}if(time>=total)playing=false;active=-1;update(true);draw()}
function toggle(){playing?pause():start()}
function frame(now){let dt=Math.min(.1,(now-(last||now))/1000);last=now;if(playing){let cue=cues[cueAt(time)],candidate=time+dt*rate;if(candidate>=cue.end&&!speechDone&&now<speechDeadline){time=cue.end-.001}else{if(!speechDone&&now>=speechDeadline){cancelSpeech();$('#status').textContent='La narración tardó demasiado; continúa la animación con subtítulos.'}time=Math.min(candidate,total);if(time>=total){playing=false;cancelSpeech()}}update();draw()}requestAnimationFrame(frame)}
$('#seek').max=total;$('#durationIntro').textContent=`${Math.round(total/60)} min`;$('#markers').innerHTML=chapters.slice(1).map(c=>`<i style="left:${c.start/total*100}%"></i>`).join('');$('#chapterList').innerHTML=chapters.map((ch,i)=>`<button class="chapter" data-chapter="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${ch.title}</strong><small>${clock(ch.start)} · ${clock(ch.end-ch.start)}</small></span></button>`).join('');
$('#chapterList').onclick=e=>{let b=e.target.closest('[data-chapter]');if(!b)return;seek(chapters[+b.dataset.chapter].start);setChapters(false)};
function setChapters(open){$('#chapters').hidden=!open;$('#chaptersBtn').setAttribute('aria-expanded',String(open));if(open)$('#closeChapters').focus();else $('#chaptersBtn').focus()}
$('#chaptersBtn').onclick=()=>setChapters($('#chapters').hidden);$('#closeChapters').onclick=()=>setChapters(false);$('#play').onclick=toggle;$('#start').onclick=start;$('#back').onclick=()=>seek(time-10);$('#forward').onclick=()=>seek(time+10);$('#seek').oninput=e=>seek(+e.target.value);$('#repeat').onclick=()=>seek(chapters[cues[cueAt(time)].ci].start);$('#replay').onclick=()=>{seek(0);start()};$('#voice').onclick=()=>{voice=!voice;$('#voice').textContent=`Voz: ${voice?'sí':'no'}`;$('#voice').setAttribute('aria-pressed',String(voice));cancelSpeech();if(voice&&playing)speak(cues[cueAt(time)])};$('#cc').onclick=()=>{captions=!captions;$('#cc').setAttribute('aria-pressed',String(captions));$('#caption').hidden=!captions||!started};$('#speed').onchange=e=>{rate=+e.target.value;if(playing)speak(cues[cueAt(time)])};
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#player').requestFullscreen)await $('#player').requestFullscreen();else $('#status').textContent='Este navegador no permite pantalla completa. Gira el dispositivo para ampliar la escena.'}catch{$('#status').textContent='No se pudo abrir pantalla completa en este navegador.'}}$('#full').onclick=fullscreen;
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON','A'].includes(e.target.tagName)||$('#mathDialog').open||$('#zoomDialog').open)return;if(e.code==='Space'){e.preventDefault();toggle()}else if(e.key==='ArrowRight'){e.preventDefault();seek(time+10)}else if(e.key==='ArrowLeft'){e.preventDefault();seek(time-10)}else if(e.key.toLowerCase()==='f')fullscreen();else if(e.key.toLowerCase()==='r')$('#repeat').click();else if(e.key==='Escape')setChapters(false)});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){pause();$('#status').textContent='Pausado al salir de la pestaña. Pulsa reproducir para continuar.'}});
$('#zoom').onclick=()=>{$('#zoomDialog').showModal();draw();$('#zoomDialog .zoom-scroll').scrollLeft=180};$('#closeZoom').onclick=()=>$('#zoomDialog').close();
$('#mathBtn').onclick=()=>{pause();$('#mathDialog').showModal()};$('#closeMath').onclick=()=>$('#mathDialog').close();
const formatMatrix=m=>m.map(r=>'[ '+r.map(x=>f(x)).join(', ')+' ]').join('\n');$('#mathData').textContent=[['E (embeddings)',E],['PE (posición)',[pe(0),pe(1),pe(2)]],['X = E + PE',X],['WQ',WQ],['WK',WK],['WV',WV],['Q = XWQ',Q],['K = XWK',K],['V = XWV',V],['S = QKᵀ',S],['A = softmax(S / 2)',A],['Z = AV',Z],['WO',WO],['Residual 1',[res]],['LayerNorm 1',[ln]],['W1',W1],['Ocultas',[hidden]],['ReLU',[relu]],['W2',W2],['FFN',[ff]],['Residual 2',[res2]],['Y3 = LayerNorm',[Y]]].map(([k,m])=>k+'\n'+formatMatrix(m)).join('\n\n');
// Read-only numeric and timeline metadata for reproducible verification.
window.transformerLesson={X,WQ,WK,WV,WO,W1,W2,Q,K,V,S,A,Z,a,res,ln,hidden,relu,ff,res2,Y,E,chapters,total};
update();draw();requestAnimationFrame(frame);
})();
