(()=>{'use strict';
const $=s=>document.querySelector(s),S=window.Story,D=window.FilmDrawing,M=window.Model;
let t=0,playing=false,started=false,voice=true,rate=1,active=-1,last=performance.now(),zoomed=false;
let utterance=null,speechFinished=true,speechPaused=false,version=0,deadline=0,pausedAt=0;
let dragStart=null;
const clock=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function indexAt(time){let lo=0,hi=S.scenes.length-1;while(lo<hi){let mid=Math.floor((lo+hi)/2);if(time>=S.scenes[mid].end)lo=mid+1;else hi=mid}return lo}
function stopSpeech(){version++;speechFinished=true;speechPaused=false;utterance=null;if('speechSynthesis'in window)speechSynthesis.cancel()}
function speak(scene){stopSpeech();if(!voice||!playing)return;if(!('speechSynthesis'in window)){$('#status').textContent='La voz no está disponible aquí. Puedes seguir la explicación con subtítulos.';return}let v=version;utterance=new SpeechSynthesisUtterance(scene.text);const voices=speechSynthesis.getVoices();utterance.voice=voices.find(v=>v.lang==='es-CO')||voices.find(v=>v.lang==='es-MX')||voices.find(v=>v.lang.startsWith('es'))||null;utterance.lang=utterance.voice?.lang||'es-ES';utterance.rate=rate;utterance.pitch=1;speechFinished=false;deadline=performance.now()+Math.max(18000,scene.duration*2400/rate);utterance.onend=()=>{if(v===version)speechFinished=true};utterance.onerror=event=>{if(v===version){speechFinished=true;if(!['interrupted','canceled'].includes(event.error))$('#status').textContent='No se pudo reproducir la voz. Los subtítulos y las animaciones continúan.'}};speechSynthesis.speak(utterance)}
function render(){const i=indexAt(t),s=S.scenes[i],progress=Math.max(0,Math.min(1,(t-s.start)/s.duration));D.draw(s,progress,started);$('#timeline').value=t;$('#time').textContent=`${clock(t)} / ${clock(S.total)}`;$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',playing?'Pausar':'Reproducir');$('#ending').hidden=t<S.total;$('#back').disabled=t<=0;$('#next').disabled=t>=S.total;if(i!==active){active=i;$('#subtitle').textContent=started?s.text:'Pulsa reproducir. La explicación y los dibujos avanzan juntos.';$('#chapterTitle').textContent=started?`${String(s.chapter+1).padStart(2,'0')} / ${S.chapters[s.chapter].name}`:'UNA IDEA, DIBUJADA A LA VEZ';document.querySelectorAll('.chapter').forEach((b,j)=>b.classList.toggle('active',j===s.chapter));if(playing)speak(s)}}
function start(){if(!started){started=true;$('#cover').hidden=true;active=-1}if(t>=S.total){t=0;active=-1}playing=true;last=performance.now();if(speechPaused&&utterance&&!speechFinished){speechPaused=false;deadline+=performance.now()-pausedAt;speechSynthesis.resume()}else{active=-1}render()}
function pause(){playing=false;if(utterance&&!speechFinished&&voice&&'speechSynthesis'in window){speechPaused=true;pausedAt=performance.now();speechSynthesis.pause()}else stopSpeech();render()}
function seek(time){stopSpeech();t=time>=S.total-.001?S.total:Math.max(0,Math.min(S.total,time));started=true;$('#cover').hidden=true;if(t>=S.total)playing=false;active=-1;render()}
function toggle(){playing?pause():start()}
function frame(now){let dt=Math.min((now-last)/1000,.12);last=now;if(playing){const s=S.scenes[indexAt(t)],candidate=t+dt*rate;if(candidate>=s.end&&!speechFinished&&now<deadline){t=s.end-.00001}else{if(!speechFinished&&now>=deadline){stopSpeech();$('#status').textContent='La voz no respondió a tiempo; la clase continúa con subtítulos.'}t=Math.min(candidate,S.total);if(t>=S.total){playing=false;stopSpeech()}}render()}requestAnimationFrame(frame)}
$('#timeline').max=S.total;$('#timeline').oninput=e=>seek(Number(e.target.value));$('#duration').textContent=`${Math.ceil(S.total/60)} min`;
$('#ticks').innerHTML=S.chapters.slice(1).map(c=>`<i style="left:${c.time/S.total*100}%"></i>`).join('');
$('#chapters').innerHTML=S.chapters.map((c,i)=>`<button class="chapter" data-chapter="${i}"><span class="n">${String(i+1).padStart(2,'0')}</span><span><strong>${c.name}</strong><small>${clock(c.time)} · ${clock(c.end-c.time)}</small></span></button>`).join('');
$('#start').onclick=start;$('#play').onclick=toggle;$('#back').onclick=()=>seek(t-10);$('#next').onclick=()=>seek(S.scenes[Math.min(S.scenes.length-1,indexAt(t)+1)].start);$('#repeat').onclick=()=>seek(S.scenes[indexAt(t)].start);$('#restart').onclick=()=>{seek(0);start()};
$('#voiceButton').onclick=()=>{voice=!voice;$('#voiceState').textContent=voice?'sí':'no';$('#voiceButton').setAttribute('aria-pressed',String(voice));stopSpeech();if(voice&&playing)speak(S.scenes[indexAt(t)])};$('#speed').onchange=e=>{rate=+e.target.value;if(playing)speak(S.scenes[indexAt(t)])};
$('#chapterButton').onclick=()=>{$('#chaptersDialog').showModal();$('#chapterButton').setAttribute('aria-expanded','true')};$('#chaptersDialog').addEventListener('close',()=>$('#chapterButton').setAttribute('aria-expanded','false'));$('#chapters').onclick=e=>{let b=e.target.closest('[data-chapter]');if(!b)return;seek(S.chapters[+b.dataset.chapter].time);$('#chaptersDialog').close()};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#dataButton').onclick=()=>{pause();$('#dataDialog').showModal()};
const entries=[['Embeddings E',M.E],['Posiciones PE',[M.pe(0),M.pe(1),M.pe(2)]],['X = E + PE',M.X],['WQ',M.WQ],['WK',M.WK],['WV',M.WV],['Q = XWQ',M.Q],['K = XWK',M.K],['V = XWV',M.V],['Scores QKᵀ',M.S],['A = softmax(S / 2)',M.A],['Z = AV',M.Z],['Wᴼ',M.WO],['Residual 1',[M.res]],['LayerNorm 1',[M.ln]],['W₁',M.W1],['Activaciones',[M.hidden]],['ReLU',[M.relu]],['W₂',M.W2],['FFN',[M.ff]],['Residual 2',[M.res2]],['Salida del bloque Y₃',[M.Y]],['W vocabulario: columnas [punto, y, pero, fin]',M.Wvocab],['Logits',[M.logits]],['Probabilidades',[M.probabilities]]];
$('#data').innerHTML=entries.map(([name,mat])=>`<details><summary>${name}</summary><pre>${mat.map(r=>'[ '+r.map(v=>M.f(v,6)).join(', ')+' ]').join('\n')}</pre></details>`).join('');
function zoom(){zoomed=!zoomed;D.setZoom(zoomed);$('#zoom').setAttribute('aria-pressed',String(zoomed));$('#zoom').textContent=zoomed?'⊖':'⊕';$('#pointerHint').hidden=!zoomed;render()}$('#zoom').onclick=zoom;
$('#canvas').addEventListener('pointerdown',ev=>{if(!zoomed)return;dragStart={x:ev.clientX,y:ev.clientY};$('#canvas').setPointerCapture(ev.pointerId)});$('#canvas').addEventListener('pointermove',ev=>{if(!zoomed||!dragStart)return;D.drag(ev.clientX-dragStart.x,ev.clientY-dragStart.y);dragStart={x:ev.clientX,y:ev.clientY};render()});$('#canvas').addEventListener('pointerup',()=>dragStart=null);$('#canvas').addEventListener('pointercancel',()=>dragStart=null);$('#canvas').ondblclick=()=>{if(zoomed)zoom()};
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#player').requestFullscreen)await $('#player').requestFullscreen();else $('#status').textContent='Puedes girar tu dispositivo para ampliar la clase.'}catch{$('#status').textContent='Este navegador no permite pantalla completa.'}}$('#fullscreen').onclick=fullscreen;
document.addEventListener('keydown',ev=>{if(document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes(ev.target.tagName))return;if(ev.code==='Space'){ev.preventDefault();toggle()}else if(ev.key==='ArrowRight'){ev.preventDefault();seek(t+10)}else if(ev.key==='ArrowLeft'){ev.preventDefault();seek(t-10)}else if(ev.key.toLowerCase()==='f')fullscreen();else if(ev.key.toLowerCase()==='r')$('#repeat').click()});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause()});window.addEventListener('pagehide',stopSpeech);
const observer=new ResizeObserver(()=>{D.resize();render()});observer.observe($('#stage'));D.resize();render();requestAnimationFrame(frame);
window.Film={version:'2.0',story:S,model:M,state:()=>({time:t,playing,started,scene:indexAt(t),speechFinished,zoomed,voice})};
})();
